<?xml version="1.0" encoding="utf-8"?><Database Name="GestionPedidos" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=USUARIO-PC\SQLMICHAEL;Initial Catalog=GestionPedidos;Integrated Security=True" SettingsObjectName="C32_LINQ_SQLServer.Properties.Settings" SettingsPropertyName="GestionPedidosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Empresa_Empleado" Member="Empleado" ThisKey="id" OtherKey="idEmpresa" Type="Empleado" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleado">
    <Type Name="Empleado">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Empleado_CargoEmpleado" Member="CargoEmpleado" ThisKey="id" OtherKey="idEmpleado" Type="CargoEmpleado" />
      <Association Name="Empresa_Empleado" Member="Empresa" ThisKey="idEmpresa" OtherKey="id" Type="Empresa" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cargo" Member="Cargo">
    <Type Name="Cargo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_CargoEmpleado" Member="CargoEmpleado" ThisKey="id" OtherKey="idCargo" Type="CargoEmpleado" />
    </Type>
  </Table>
  <Table Name="dbo.CargoEmpleado" Member="CargoEmpleado">
    <Type Name="CargoEmpleado">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCargo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_CargoEmpleado" Member="Cargo" ThisKey="idCargo" OtherKey="id" Type="Cargo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Empleado_CargoEmpleado" Member="Empleado" ThisKey="idEmpleado" OtherKey="id" Type="Empleado" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>